---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install Meraki SDK
      ansible.builtin.command:
        cmd: pip3 install meraki


    - name: Get all Organizations
      cisco.meraki.organizations_info:
        meraki_suppress_logging: false
        meraki_api_key: "{{ lookup('env', 'MERAKI_API_KEY') }}"
        organizationId: "{{ lookup('env', 'ORG_ID') }}"
      register: result

    - name: Show result
      ansible.builtin.debug:
        msg: "{{ result }}"
