---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Get administered identities for me
      cisco.meraki.administered_identities_me_info:
        meraki_suppress_logging: true
        meraki_api_key: "{{ lookup('env', 'MERAKI_API_KEY') }}"
      register: me

    - name: Show current Meraki administrator
      ansible.builtin.debug:
        msg: "{{ me.meraki_response.name }} - {{ me.meraki_response.email }}"

    - name: Get all Organizations
      cisco.meraki.organizations_info:
        meraki_suppress_logging: true
        meraki_api_key: "{{ lookup('env', 'MERAKI_API_KEY') }}"
      register: result

    - name: Show Organizations List
      ansible.builtin.debug:
        msg: "{{ result | json_query('meraki_response[*].name') }}"
